### ISSUE TITLE
Don't install on CentOS

### ISSUE THREAD

**Issue by SmookeyDev** [Matoking/nanolib#10]
Collecting nanolib
  Using cached https://files.pythonhosted.org/packages/db/a8/af0f8110b7a40c65e10d0e0c635fc4b338bd9cd7e07d5b50cbee41c00202/nanolib-0.4.2.tar.gz
Collecting ed25519-blake2b>=1.4 (from nanolib)
  Using cached https://files.pythonhosted.org/packages/1d/f1/035bafb5b2ed5b379abd4bf26ebad6e9fed73e21756971cefe027bd55ec2/ed25519-blake2b-1.4.tar.gz
Collecting py-cpuinfo>=4 (from nanolib)
  Using cached https://files.pythonhosted.org/packages/f6/f5/8e6e85ce2e9f6e05040cf0d4e26f43a4718bcc4bce988b433276d4b1a5c1/py-cpuinfo-7.0.0.tar.gz
Installing collected packages: ed25519-blake2b, py-cpuinfo, nanolib
  Running setup.py install for ed25519-blake2b ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bmrg6xzj/ed25519-blake2b/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v42xaj_n-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ed25519_blake2b
    copying src/ed25519/_version.py -> build/lib.linux-x86_64-3.6/ed25519_blake2b
    copying src/ed25519/test_ed25519.py -> build/lib.linux-x86_64-3.6/ed25519_blake2b
    copying src/ed25519/__init__.py -> build/lib.linux-x86_64-3.6/ed25519_blake2b
    copying src/ed25519/keys.py -> build/lib.linux-x86_64-3.6/ed25519_blake2b
    UPDATING build/lib.linux-x86_64-3.6/ed25519_blake2b/_version.py
    set build/lib.linux-x86_64-3.6/ed25519_blake2b/_version.py to '1.4'
    running build_ext
    building 'ed25519_blake2b._ed25519' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/ed25519-glue
    creating build/temp.linux-x86_64-3.6/src/ed25519-supercop-ref
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/ed25519-supercop-ref -I/usr/include/python3.6m -c src/ed25519-glue/ed25519module.c -o build/temp.linux-x86_64-3.6/src/ed25519-glue/ed25519module.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bmrg6xzj/ed25519-blake2b/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v42xaj_n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bmrg6xzj/ed25519-blake2b/

**Comment by Matoking** [comment]
You need a working build environment and Python headers to compile C extensions for Python. The following should hopefully do the trick:

```
sudo yum groupinstall "Development tools"
sudo yum install python3-devel
```

**Comment by SmookeyDev** [comment]
After installing these packages, presented another error:

Collecting nanolib
  Using cached https://files.pythonhosted.org/packages/db/a8/af0f8110b7a40c65e10d0e0c635fc4b338bd9cd7e07d5b50cbee41c00202/nanolib-0.4.2.tar.gz
Collecting ed25519-blake2b>=1.4 (from nanolib)
  Using cached https://files.pythonhosted.org/packages/1d/f1/035bafb5b2ed5b379abd4bf26ebad6e9fed73e21756971cefe027bd55ec2/ed25519-blake2b-1.4.tar.gz
Collecting py-cpuinfo>=4 (from nanolib)
  Using cached https://files.pythonhosted.org/packages/f6/f5/8e6e85ce2e9f6e05040cf0d4e26f43a4718bcc4bce988b433276d4b1a5c1/py-cpuinfo-7.0.0.tar.gz
Installing collected packages: ed25519-blake2b, py-cpuinfo, nanolib
  Running setup.py install for ed25519-blake2b ... done
  Running setup.py install for py-cpuinfo ... done
  Running setup.py install for nanolib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_w0r5_8v/nanolib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ywin5wqt-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/work.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/_version.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/blocks.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/exceptions.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/__init__.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/accounts.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/util.py -> build/lib.linux-x86_64-3.6/nanolib
    copying src/nanolib/units.py -> build/lib.linux-x86_64-3.6/nanolib
    running egg_info
    writing nanolib.egg-info/PKG-INFO
    writing dependency_links to nanolib.egg-info/dependency_links.txt
    writing requirements to nanolib.egg-info/requires.txt
    writing top-level names to nanolib.egg-info/top_level.txt
    reading manifest file 'nanolib.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'requirements_dev.txt'
    warning: no previously-included files found matching '*.yml'
    warning: no previously-included files found matching 'src/nanolib-work-module/README.md'
    no previously-included directories found matching 'docs'
    no previously-included directories found matching 'tests'
    no previously-included directories found matching 'examples'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'nanolib.egg-info/SOURCES.txt'
    UPDATING build/lib.linux-x86_64-3.6/nanolib/_version.py
    set build/lib.linux-x86_64-3.6/nanolib/_version.py to '0.4.2'
    running build_ext
    building 'nanolib._work_avx' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/nanolib-work-module
    creating build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2
    creating build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/work.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o -DWORK_AVX -mavx
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2b.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o -DWORK_AVX -mavx
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2bp.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -DWORK_AVX -mavx
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/nanolib/_work_avx.cpython-36m-x86_64-linux-gnu.so
    building 'nanolib._work_sse4_1' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/work.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o -DWORK_SSE4_1 -msse4.1
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2b.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o -DWORK_SSE4_1 -msse4.1
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2bp.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -DWORK_SSE4_1 -msse4.1
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/nanolib/_work_sse4_1.cpython-36m-x86_64-linux-gnu.so
    building 'nanolib._work_ssse3' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/work.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o -DWORK_SSSE3 -mssse3
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2b.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o -DWORK_SSSE3 -mssse3
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2bp.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -DWORK_SSSE3 -mssse3
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/nanolib/_work_ssse3.cpython-36m-x86_64-linux-gnu.so
    building 'nanolib._work_sse2' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/work.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o -DWORK_SSE2 -msse2
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2b.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o -DWORK_SSE2 -msse2
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/sse -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/sse/blake2bp.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -DWORK_SSE2 -msse2
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2b.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/sse/blake2bp.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/nanolib/_work_sse2.cpython-36m-x86_64-linux-gnu.so
    building 'nanolib._work_ref' extension
    creating build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/ref
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/ref -I/usr/include/python3.6m -c src/nanolib-work-module/work.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o -DWORK_REF
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/ref -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/ref/blake2bp-ref.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/ref/blake2bp-ref.o -DWORK_REF
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-work-module/BLAKE2/ref -I/usr/include/python3.6m -c src/nanolib-work-module/BLAKE2/ref/blake2b-ref.c -o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/ref/blake2b-ref.o -DWORK_REF
    gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/nanolib-work-module/work.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/ref/blake2bp-ref.o build/temp.linux-x86_64-3.6/src/nanolib-work-module/BLAKE2/ref/blake2b-ref.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/nanolib/_work_ref.cpython-36m-x86_64-linux-gnu.so
    building 'nanolib._nbase32' extension
    creating build/temp.linux-x86_64-3.6/src/nanolib-nbase32-module
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/nanolib-nbase32-module -I/usr/include/python3.6m -c src/nanolib-nbase32-module/nbase32.c -o build/temp.linux-x86_64-3.6/src/nanolib-nbase32-module/nbase32.o
    src/nanolib-nbase32-module/nbase32.c: In function ‘nbase32_to_bytes’:
    src/nanolib-nbase32-module/nbase32.c:57:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint64_t i=0; i < bitarr_bits; i += NBASE32_CHAR_BITS) {
         ^
    src/nanolib-nbase32-module/nbase32.c:57:5: note: use option -std=c99 or -std=gnu99 to compile your code
    src/nanolib-nbase32-module/nbase32.c:73:19: error: redefinition of ‘i’
         for (uint64_t i=leftover; i < bitarr_bits; i += 8) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:57:19: note: previous definition of ‘i’ was here
         for (uint64_t i=0; i < bitarr_bits; i += NBASE32_CHAR_BITS) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:73:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint64_t i=leftover; i < bitarr_bits; i += 8) {
         ^
    src/nanolib-nbase32-module/nbase32.c: In function ‘bytes_to_nbase32’:
    src/nanolib-nbase32-module/nbase32.c:100:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint64_t i=leftover; i < bitarr_bits; i += 8) {
         ^
    src/nanolib-nbase32-module/nbase32.c:113:19: error: redefinition of ‘i’
         for (uint64_t i=0; i < bitarr_bits; i += 5) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:100:19: note: previous definition of ‘i’ was here
         for (uint64_t i=leftover; i < bitarr_bits; i += 8) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:113:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint64_t i=0; i < bitarr_bits; i += 5) {
         ^
    src/nanolib-nbase32-module/nbase32.c:130:19: error: redefinition of ‘i’
         for (uint64_t i=start; i < result_size + start; i++) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:113:19: note: previous definition of ‘i’ was here
         for (uint64_t i=0; i < bitarr_bits; i += 5) {
                       ^
    src/nanolib-nbase32-module/nbase32.c:130:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint64_t i=start; i < result_size + start; i++) {
         ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_w0r5_8v/nanolib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ywin5wqt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_w0r5_8v/nanolib/
