### ISSUE TITLE
Solving work taking forever

### ISSUE THREAD

**Issue by NikEyX** [Matoking/nanolib#14]
Hi,

Solving work takes 60+ seconds for me. Any idea what could cause this?

I am also very confused as to how you get to [these benchmarks](https://github.com/Matoking/nanolib/blob/master/src/nanolib/work.py#L16):
```
 This based on a Ryzen 1800X giving the following results:
# avx speed: 6185344 hashes/s (this is likely the fastest on Intel CPUs)
# sse4_1 speed: 6259267 hashes/s
# ssse3 speed: 6249287 hashes/s
# sse2 speed: 4635929 hashes/s
# ref speed: 4539306 hashes/s
```

This is significantly faster than what I get when I run your benchmark (`python setup.py speed`):

```running speed
BLAKE2b PoW (avx) DEFAULT speed: 1653567 hashes/s
BLAKE2b PoW (sse4_1) speed: 1685205 hashes/s
BLAKE2b PoW (ssse3) speed: 1542921 hashes/s
BLAKE2b PoW (sse2) speed: 1195275 hashes/s
BLAKE2b PoW (ref) speed: 1448130 hashes/s
Account generation rate: 674 accounts/s
Block sign rate: 444 blocks/s
Block verify rate: 380 blocks/s
```

Unless you're using all cores for that? your benchmark is only single core though?

This is my CPU spec:

```
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 113
model name      : AMD Ryzen 9 3950X 16-Core Processor
stepping        : 0
microcode       : 0x8701021
cpu MHz         : 2200.000
cache size      : 512 KB
physical id     : 0
siblings        : 32
core id         : 0
cpu cores       : 16
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6989.22
TLB size        : 3072 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```
I can run nault.cc locally and send transactions every second or faster. So why the PoW generation so slow in nanolib?

**Comment by Matoking** [comment]
Yeah, those are incorrect results I forgot to update as part of b69b573f1f37125bae40af94cdc1952a4fbb406a. The actual results are 1/4 of what was reported there.

The benchmark is single-threaded, as is the `solve_work` function itself. The C extension releases the GIL, which means you can run the PoW generation on multiple cores using threads (eg. using `concurrent.futures.ThreadPoolExecutor`) and `nanolib.work.solve_work`. This is not implemented in nanolib itself, though.

As for the PoW generation being slow, the difficulty in the Nano network has been increased since nanolib was first released, which could also account for it being slow if you're using the network difficulty as the target. The Nano docs also [recommend using a GPU](https://docs.nano.org/integration-guides/work-generation/#cpu-vs-gpu) if available, though that isn't supported by nanolib.

**Comment by NikEyX** [comment]
Ok, thanks. I already moved to multi-threaded and can confirm that it works well indeed. I think it would be nice to have this as out-of-the-box feature in nanolib, especially since it's quite trivial to implement. 

The nano PoW being slow really confused me, because I know the target was originally that the PoW can be generated on a mobile phone in under 1 second, but that has clearly changed. Multi-threaded on 16 cores (without GPU) takes on average 3 seconds now, so that's acceptable.
