### ISSUE TITLE
Lack of a list of requirements in nanolib

### ISSUE THREAD

**Issue by FilipeMarch** [Matoking/nanolib#6]
First, when I open https://github.com/Matoking/nanolib there's no place on the page saying how to import nanolib. I would suggest to put a line saying something like:
"Installation:  If you are using Linux, open terminal and type pip install nanolib"

I encountered some errors when trying to: pip install nanolib
It was necessary to type this commands first:

sudo apt install build-essential

So, we need a list of requirements in nanolib github. Also, there nothing on documentation saying how to install it properly, or what is required to install before installing Nanolib.

**Comment by Matoking** [comment]
I've added installation instructions and requirements to the README.

I may start maintaining prebuilt wheels for common platforms in the future, but a build environment will still be necessary for other platforms.
