### ISSUE TITLE
Troubles installing on aarch64

### ISSUE THREAD

**Issue by mikerow** [Matoking/nanolib#8]
Hello, I'm having troubles installing nanolib on aarch64.
I'm using Raspberry Pi 4 + Ubuntu server.

This library is a requirment in order to install pippin-wallet.

Let me know if you need more details. Good day

![error1](https://user-images.githubusercontent.com/47996463/85122303-9ebe6280-b226-11ea-8380-e66938473c6c.PNG)
![error2](https://user-images.githubusercontent.com/47996463/85122306-9fef8f80-b226-11ea-8c81-abfad1189ee4.PNG)

**Comment by Matoking** [comment]
Looks like the `-mfpu=neon` flag isn't supported on all 64-bit ARM platforms. Could you try installing nanolib using the following command instead:

```
pip install --upgrade git+https://github.com/Matoking/nanolib.git@fix_aarch64#egg=nanolib
```

After that, you should hopefully be able to install pippin-wallet as normal. Tell me if it works, so I can push the fix to master; I don't have a device at hand to test this myself.

**Comment by mikerow** [comment]
It has been installed succesfully, ty

<pre>
Successfully installed nanolib-0.4.1+3.g22f5293
</pre>

**Comment by Matoking** [comment]
Great, thanks for confirming.
